### PR TITLE
Fix cli option spelling.

### PR DESCRIPTION
**Pull request by theherk**

### CODE REVIEW

**Comment by alexdreptu** [comment]
Hi @theherk, the option was intentionally named like that as per [gnome-look.org](https://www.gnome-look.org/browse/cat/132/order/latest/), [xfce-look.org](https://www.xfce-look.org/browse/cat/132/order/latest/) and [store.kde.org](https://store.kde.org/browse/cat/132/order/latest/). It's not a misspell.

**Comment by theherk** [comment]
Okay, well would you like me to fix it in the code then? This documentation gives the option with the "s", and the code expects it without, just like the gtk2 option.

**Comment by alexdreptu** [comment]
That is indeed a typo in the documentation, it should be `--no-gtk3-icon-theme`

**Comment by theherk** [comment]
I'm slightly confused by your response. If it is not correct in the documentation, then merging this will correct it. Thanks for righting the tool.

**Comment by alexdreptu** [comment]
I'm sorry it's my mistake, it was very early morning here and didn't see the file and diff right. I thought you meant the cmdline flag.

**Comment by alexdreptu** [comment]
Thanks for the PR.

**Pull request merged**
